dist: xenial
language: node_js
node_js:
  - "8" # Also included in .nvmrc, but this saves a few seconds
git:
  depth: 10
branches:
  except:
    - "/^chore/bump-.*$/" # Avoid hookbot double-builds
notifications:
  email: false

stages:
  - name: Build
    if: type = pull_request

install:
  - yarn install --frozen-lockfile
jobs:
  include:
    - stage: Build
      name: Build and Upload Preview
      script:
        - yarn build
        - yarn build:docs
        - .circleci/release.sh
        - yarn build:storybook
        - mv .out .public/patternfly-3
        - mv packages/patternfly-4/react-docs/public .public/patternfly-4
        - cp .public/patternfly-4/favicon* .public
        - cp -r .public/patternfly-4/assets .public/assets
        - .circleci/upload_preview.sh

