version: 2
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - lint
      - jest_pf4_tests:
          requires:
            - build
      - jest_other_tests:
          requires:
            - build
      - integration_build:
          requires:
            - build
jobs:
  build:
    docker:
      - image: circleci/node:8.15
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - run:
          name: Install
          command: yarn install --frozen-lockfile
      - run:
          name: Debug
          command: git clean -ndfx
      - run:
          name: Build Dist
          command: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            # Paths made by `yarn install` and `yarn build`
            - node_modules
            - packages/*/node_modules
            - packages/*/dist
            - packages/patternfly-3/*/dist
            - packages/patternfly-4/*/dist
            - packages/patternfly-4/react-styles/css
  jest_pf4_tests:
    docker:
      - image: circleci/node:8.15
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: PF4 Jest Tests
          command: yarn test:pf4 --maxWorkers=2
  jest_other_tests:
    docker:
      - image: circleci/node:8.15
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: PF3 Jest Tests
          command: yarn test:pf3 --maxWorkers=2
      - run:
          name: Other Tests
          command: yarn test:misc --maxWorkers=2
  integration_build:
    docker:
      - image: circleci/node:8.15
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build Cypress Integration Tests
          command: yarn build:integration
  lint:
    docker:
      - image: circleci/node:8.15
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: TSLint
          command: yarn lint:ts
      - run:
          name: ESLint
          command: yarn lint:js
      - run:
          name: "@patternfly/patternfly Versions Match"
          command: yarn lint:versions
      - run:
          name: StyleLint
          command: yarn lint:style

#      - run:
#          name: (PF3) Build Storybook
#          command: |
#            yarn build:storybook &&
#            cp -r .out .public/patternfly-3
#      - run:
#          name: (PF4) Build Docs
#          command: |
#            yarn build:docs &&
#            cp -r packages/patternfly-4/react-docs/public .public/patternfly-4 &&
#            cp -r .public/patternfly-4/assets .public/assets &&
#            cp .public/patternfly-4/favicon* .public
#      - run:
#          name: Deploy Docs
#          command: if [ -n "$CIRCLE_PULL_REQUEST" ]; then .circleci/upload_preview.sh; fi