version: 2
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - jest_pf4_tests:
          requires:
            - build
jobs:
  build:
    docker:
      - image: circleci/node:8.15
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - run:
          name: Install
          command: yarn install --frozen-lockfile
      - run:
          name: Build Dist
          command: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            # Paths made by `yarn install` and `yarn build`
            - node_modules
            - packages/*/node_modules
            - packages/*/dist
            - packages/patternfly-3/*/dist
            - packages/patternfly-4/*/dist
            - packages/patternfly-4/react-styles/css
              #      - run:
              #          name: (PF3) Build Storybook
              #          command: |
              #            yarn build:storybook &&
              #            cp -r .out .public/patternfly-3
              #      - run:
              #          name: (PF4) Build Docs
              #          command: |
              #            yarn build:docs &&
              #            cp -r packages/patternfly-4/react-docs/public .public/patternfly-4 &&
              #            cp -r .public/patternfly-4/assets .public/assets &&
              #            cp .public/patternfly-4/favicon* .public
              #      - run:
              #          name: Deploy Docs
              #          command: if [ -n "$CIRCLE_PULL_REQUEST" ]; then .circleci/upload_preview.sh; fi
  jest_pf4_tests:
    docker:
      - image: circleci/node:8.15
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v{{ .Environment.CACHE_VERSION }}-build-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - attach_workspace:
          at: ~/repo
      - run:
          name: Jest Tests
          command: yarn test:pf4

